### ISSUE TITLE
Not loading any documents from collection

### ISSUE THREAD

**Issue by manuelmateus16** [alethes/meteor-pages#52]
I am having difficulties implementing the pagination on my meteor app and I would like you to help me solving this problem.

So my meteor app has the following directory structure:

- server folder:
  ---server.js
- client folder:
  ---client.js
  ---client.html
- common.js

In common.js:
```
PassatemposBD = new Meteor.Collection("passatempos");
Pages = new Meteor.Pagination("PassatemposBD") 
```

Then, in server.js I fill this collection with documents which I fetch from the web (takes around 30 seconds to fill). Then I publish it:
```
Meteor.publish('passatempos', function() {
    return PassatemposBD.find({});
});
```
Then in client.js:
```
Meteor.subscribe('passatempos');
```
In client.html
```
<body>
<div> Passatempos:</div>
    {{> PassatemposBD}}
</body>
<template name="PassatemposBD">
    {{> pages}}
    {{> pagesNav}}  <!--Bottom navigation-->
</template>
```
When I run the app, it displays for a brief time (1 second or less) the rotating spin, then simply doesn't show nothing, neither the navigation below. In the browser console there is no error, neither there are errors in the server side.

Can you explain me what am I doing wrong? 

Thanks

**Comment by alethes** [comment]
The `Pagination` object handles subscriptions on its own. The issue was likely related to additional `publish` and `subscribe` calls in your code.

---
By the way, in the older versions, the automatically created subscriptions had the same name as the paginated collection. In the recent releases, the name has been prefixed with a `pages`-specific string. This means you can now create an additional subscription named after your collection and use it outside of `pages`, if needed. Still, for `pages`-related operations, the `publish` and `subscribe` calls are handled internally and there's no need to do them by yourself.

**Comment by Shelagh-Lewins** [comment]
I have the same problem and I can't figure it out from your answer above. If I don't use an existing collection then obviously there is no data: if I don't publish and subscribe to that collection then no other part of my app can access the data. Everything I've tried leads to an error or just no results. Please, can you give an example that explains how to use this in a real app where you are using an existing collection?

**Comment by Shelagh-Lewins** [comment]
Ah, I think I have cracked it. Your template needs to be named "passatempos" not "PassatemposBD", that is it needs to be named for the collection not the variable that holds the collection. That seems to be how Meteor Pages identifies which template to use.

This could usefully be made more clear in the examples.
